version: '3.8'

services:

  frontend:
    build: ./FRONTEND/my-app
    restart: always
    container_name: frontend_container
    ports:
      - "3000:3000"

  auth-server:
    build: ./BACKEND-dockers/authServer
    restart: always
    container_name: authserver_container
    ports:
      - "4000:4000"

  root-server:
    build: ./BACKEND-dockers/rootServer
    restart: always
    container_name: rootserver_container
    ports:
      - "3001:3001"

  crudapi-server:
    build: ./BACKEND-dockers/crudapiServer
    restart: always
    container_name: crudapiserver_container
    ports:
      - "4001:4001"

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
