version: '3.8'

services:
  frontend:
    build: ./FRONTEND/my-app
    restart: always
    container_name: frontend_container
    ports:
      - "3000:3000"
    networks:
      - my-network

  auth-server:
    build: ./BACKEND-dockers/authServer
    restart: always
    container_name: authserver_container
    ports:
      - "4000:4000"
    networks:
      - my-network

  root-server:
    build: ./BACKEND-dockers/rootServer
    restart: always
    container_name: rootserver_container
    ports:
      - "3001:3001"
    networks:
      - my-network

  second-server:
    build: ./BACKEND-dockers/secondpageServer
    restart: always
    container_name: secondpageServer_container
    ports:
      - "4001:4001"
    networks:
      - my-network

  mysql:
    build:
      context: ./BACKEND-dockers/mysql-custom
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge
