

#### 1.2 if valid user Authserver 
#req both username and password but use only username
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "user1"
}


#### 1 login   RootAPI server (http://localhost:3000/)
POST http://localhost:3001/login-check
Content-Type: application/json

{
    "username": "user1",
    "password": "password1"
}

##### 2 crud   CRUD Server (http://localhost:3000/collab-writing-platform)

GET http://localhost:4001/protectedpath
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQkVOMiIsImlhdCI6MTcxNjQ1NDY2MX0.XbSxWmHdOPvmbx7h91shJXTy6TmL84wC5NzXPr2ju6s

